name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Service Registry
        run: |
          cd ServiceRegistry
          mvn clean install -Dmaven.test.skip=true

      - name: Build API Gateway
        run: |
          cd API-Gateway
          mvn clean install -Dmaven.test.skip=true

      - name: Build User Service
        run: |
          cd UserService
          mvn clean install -Dmaven.test.skip=true

      - name: Build Flight Service
        run: |
          cd FlightService
          mvn clean install -Dmaven.test.skip=true

      - name: Build Booking Service
        run: |
          cd BookingService
          mvn clean install -Dmaven.test.skip=true

      - name: Build Payment Service
        run: |
          cd PaymentService
          mvn clean install -Dmaven.test.skip=true

      - name: Build Notification Service
        run: |
          cd NotificationService
          mvn clean install -Dmaven.test.skip=true

      - name: Verify Docker Compose Build
        run: docker compose build